#pragma once

// From glfw3.h
#define GBOX_MOUSE_BUTTON_1         0
#define GBOX_MOUSE_BUTTON_2         1
#define GBOX_MOUSE_BUTTON_3         2
#define GBOX_MOUSE_BUTTON_4         3
#define GBOX_MOUSE_BUTTON_5         4
#define GBOX_MOUSE_BUTTON_6         5
#define GBOX_MOUSE_BUTTON_7         6
#define GBOX_MOUSE_BUTTON_8         7
#define GBOX_MOUSE_BUTTON_LAST      GBOX_MOUSE_BUTTON_8
#define GBOX_MOUSE_BUTTON_LEFT      GBOX_MOUSE_BUTTON_1
#define GBOX_MOUSE_BUTTON_RIGHT     GBOX_MOUSE_BUTTON_2
#define GBOX_MOUSE_BUTTON_MIDDLE    GBOX_MOUSE_BUTTON_3